apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: users
  labels:
    app: user-service
  annotations:
   com.datadoghq.ad.logs: '[{"source": "nodejs","service":"users_eks"}]'
spec:
  type: LoadBalancer
  selector: 
    app: users-eks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      